//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMarket.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoMarket.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додавання оголошення.
        /// </summary>
        public static string AddListingTitle {
            get {
                return ResourceManager.GetString("AddListingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всі.
        /// </summary>
        public static string ConditionAll {
            get {
                return ResourceManager.GetString("ConditionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нові.
        /// </summary>
        public static string ConditionNew {
            get {
                return ResourceManager.GetString("ConditionNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вживані.
        /// </summary>
        public static string ConditionUsed {
            get {
                return ResourceManager.GetString("ConditionUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участь у ДТП.
        /// </summary>
        public static string FieldAccident {
            get {
                return ResourceManager.GetString("FieldAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Торг.
        /// </summary>
        public static string FieldBargain {
            get {
                return ResourceManager.GetString("FieldBargain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип кузова.
        /// </summary>
        public static string FieldBodyType {
            get {
                return ResourceManager.GetString("FieldBodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Місто.
        /// </summary>
        public static string FieldCity {
            get {
                return ResourceManager.GetString("FieldCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колір.
        /// </summary>
        public static string FieldColor {
            get {
                return ResourceManager.GetString("FieldColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технічний стан.
        /// </summary>
        public static string FieldCondition {
            get {
                return ResourceManager.GetString("FieldCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер автомобіля.
        /// </summary>
        public static string FieldLicensePlate {
            get {
                return ResourceManager.GetString("FieldLicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марка авто.
        /// </summary>
        public static string FieldMake {
            get {
                return ResourceManager.GetString("FieldMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пробіг.
        /// </summary>
        public static string FieldMileage {
            get {
                return ResourceManager.GetString("FieldMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        public static string FieldMileagePlaceholder {
            get {
                return ResourceManager.GetString("FieldMileagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на км.
        /// </summary>
        public static string FieldMileageUnit {
            get {
                return ResourceManager.GetString("FieldMileageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель авто.
        /// </summary>
        public static string FieldModel {
            get {
                return ResourceManager.GetString("FieldModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ціна.
        /// </summary>
        public static string FieldPriceLabel {
            get {
                return ResourceManager.GetString("FieldPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        public static string FieldPricePlaceholder {
            get {
                return ResourceManager.GetString("FieldPricePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регіон.
        /// </summary>
        public static string FieldRegion {
            get {
                return ResourceManager.GetString("FieldRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обмін.
        /// </summary>
        public static string FieldTrade {
            get {
                return ResourceManager.GetString("FieldTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип транспорту.
        /// </summary>
        public static string FieldVehicleType {
            get {
                return ResourceManager.GetString("FieldVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рік випуску.
        /// </summary>
        public static string FieldYear {
            get {
                return ResourceManager.GetString("FieldYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марка.
        /// </summary>
        public static string FilterMake {
            get {
                return ResourceManager.GetString("FilterMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        public static string FilterModel {
            get {
                return ResourceManager.GetString("FilterModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість.
        /// </summary>
        public static string FilterPrice {
            get {
                return ResourceManager.GetString("FilterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регіон.
        /// </summary>
        public static string FilterRegion {
            get {
                return ResourceManager.GetString("FilterRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коробка передач.
        /// </summary>
        public static string FilterTransmission {
            get {
                return ResourceManager.GetString("FilterTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип транспорту.
        /// </summary>
        public static string FilterVehicleType {
            get {
                return ResourceManager.GetString("FilterVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рік випуску.
        /// </summary>
        public static string FilterYear {
            get {
                return ResourceManager.GetString("FilterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пальне.
        /// </summary>
        public static string FuelFilterText {
            get {
                return ResourceManager.GetString("FuelFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гарячі пропозиції.
        /// </summary>
        public static string HotOffersLabel {
            get {
                return ResourceManager.GetString("HotOffersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мову інтерфейсу було успішно оновлено..
        /// </summary>
        public static string LanguageChangeMessage {
            get {
                return ResourceManager.GetString("LanguageChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мову змінено.
        /// </summary>
        public static string LanguageChangeTitle {
            get {
                return ResourceManager.GetString("LanguageChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наприклад, АА 1234 ВВ.
        /// </summary>
        public static string LicensePlatePlaceholder {
            get {
                return ResourceManager.GetString("LicensePlatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати фото.
        /// </summary>
        public static string ListingAddPhoto {
            get {
                return ResourceManager.GetString("ListingAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я згоден з умовами.
        /// </summary>
        public static string ListingAgreeTerms {
            get {
                return ResourceManager.GetString("ListingAgreeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на км.
        /// </summary>
        public static string ListingMileageUnit {
            get {
                return ResourceManager.GetString("ListingMileageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угода про надання послуг.
        /// </summary>
        public static string ListingServiceAgreement {
            get {
                return ResourceManager.GetString("ListingServiceAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на щоб автоматично заповнити....
        /// </summary>
        public static string ListingStep1Subtitle {
            get {
                return ResourceManager.GetString("ListingStep1Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додайте 2-3 фото....
        /// </summary>
        public static string ListingStep1Title {
            get {
                return ResourceManager.GetString("ListingStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * Поля обов&apos;язкові....
        /// </summary>
        public static string ListingStep2Subtitle {
            get {
                return ResourceManager.GetString("ListingStep2Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основна інформація.
        /// </summary>
        public static string ListingStep2Title {
            get {
                return ResourceManager.GetString("ListingStep2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напишіть опис вашого транспорту(напр. стан, історія, обслуговування)....
        /// </summary>
        public static string ListingStep3Subtitle {
            get {
                return ResourceManager.GetString("ListingStep3Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опис автомобіля.
        /// </summary>
        public static string ListingStep3Title {
            get {
                return ResourceManager.GetString("ListingStep3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характеристики авто.
        /// </summary>
        public static string ListingStep4Title {
            get {
                return ResourceManager.GetString("ListingStep4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додаткові опції.
        /// </summary>
        public static string ListingStep5Title {
            get {
                return ResourceManager.GetString("ListingStep5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ціна, валюта, торг, обмін.
        /// </summary>
        public static string ListingStep6Subtitle {
            get {
                return ResourceManager.GetString("ListingStep6Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість.
        /// </summary>
        public static string ListingStep6Title {
            get {
                return ResourceManager.GetString("ListingStep6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розмістити оголошення.
        /// </summary>
        public static string ListingSubmitButton {
            get {
                return ResourceManager.GetString("ListingSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевірений VIN.
        /// </summary>
        public static string ListingVerifiedVin {
            get {
                return ResourceManager.GetString("ListingVerifiedVin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Головна.
        /// </summary>
        public static string PageTitleMain {
            get {
                return ResourceManager.GetString("PageTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оберіть колір.
        /// </summary>
        public static string PickerColor {
            get {
                return ResourceManager.GetString("PickerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оберіть стан.
        /// </summary>
        public static string PickerCondition {
            get {
                return ResourceManager.GetString("PickerCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оберіть.
        /// </summary>
        public static string PickerDefault {
            get {
                return ResourceManager.GetString("PickerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шукати.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чат.
        /// </summary>
        public static string TabChat {
            get {
                return ResourceManager.GetString("TabChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обране.
        /// </summary>
        public static string TabFavorites {
            get {
                return ResourceManager.GetString("TabFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Головна.
        /// </summary>
        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профіль.
        /// </summary>
        public static string TabProfile {
            get {
                return ResourceManager.GetString("TabProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продати.
        /// </summary>
        public static string TabSell {
            get {
                return ResourceManager.GetString("TabSell", resourceCulture);
            }
        }
    }
}
